#include "localization.h"

#include <cstddef>
#include <string_view>
#include <unordered_map>

namespace CoreDeck {
    namespace {
        AppLanguage currentLanguage = AppLanguage::English;

        const std::unordered_map<std::string_view, const char *> ZH_CN = {
            {"Appearance", "外观"},
            {"Visual preferences for CoreDeck.", "CoreDeck 的视觉偏好。"},
            {"Theme", "主题"},
            {"Dark", "深色"},
            {"Light", "浅色"},
            {"Language", "语言"},
            {"Font", "字体"},
            {"UI font", "界面字体"},
            {"Automatic", "自动"},
            {"Automatic (recommended)", "自动（推荐）"},
            {"Built-in fonts", "内置字体"},
            {"System candidates", "系统候选"},
            {"Manual font", "手动字体"},
            {"Choose Font...", "选择字体..."},
            {"Use Automatic", "使用自动字体"},
            {"No font candidates detected.", "未检测到可用字体。"},
            {"Selected font", "已选字体"},
            {"Built-in font", "内置字体"},
            {"Auto-detected font", "自动检测字体"},
            {"Font size", "字号"},
            {"Reset Font Size", "重置字号"},
            {"Automatic uses bundled PingFang SC Heavy. Built-in fonts are listed first, followed by system font candidates.", "自动模式使用内置 PingFang SC Heavy。内置字体优先展示，系统字体候选随后展示。"},
            {"Select a font file", "选择字体文件"},
            {"Font files", "字体文件"},
            {"The selected file is not a supported font.", "所选文件不是支持的字体。"},
            {"Selected font is no longer available.", "已选字体不再可用。"},
            {"Effective font path", "当前使用字体路径"},
            {"Choose a .ttf, .otf, or .ttc font file.", "选择 .ttf、.otf 或 .ttc 字体文件。"},
            {"General", "通用"},
            {"Behavior of CoreDeck while you work with AVDs.", "CoreDeck 操作 AVD 时的行为设置。"},
            {"Preferences", "偏好设置"},
            {"Android SDK", "Android SDK"},
            {"Java (JDK)", "Java (JDK)"},
            {"Where CoreDeck looks for the emulator and command-line tools.", "CoreDeck 查找 emulator 和命令行工具的位置。"},
            {"SDK root", "SDK 根目录"},
            {"Where CoreDeck installs and manages Android SDK command-line tools and packages.", "CoreDeck 安装和管理 Android SDK 命令行工具及软件包的位置。"},
            {"Path to Android SDK", "Android SDK 路径"},
            {"Browse...", "浏览..."},
            {"Valid Android SDK path.", "Android SDK 路径有效。"},
            {"Not a valid SDK (need emulator and cmdline-tools with avdmanager).", "不是有效 SDK（需要 emulator 和包含 avdmanager 的 cmdline-tools）。"},
            {"Leave empty to auto-detect from ANDROID_HOME or default install paths.", "留空则从 ANDROID_HOME 或默认安装路径自动检测。"},
            {"CoreDeck will use the platform default Android SDK directory.", "CoreDeck 将使用当前平台的默认 Android SDK 目录。"},
            {"Apply SDK Path", "应用 SDK 路径"},
            {"Use Default Discovery", "使用默认检测"},
            {"Fix the path or validation errors before applying.", "修复路径或验证错误后再应用。"},
            {"Forget the saved override and detect the SDK from ANDROID_HOME / default paths.", "忘记保存的覆盖路径，并从 ANDROID_HOME / 默认路径检测 SDK。"},
            {"Install Android SDK command-line tools before managing SDK packages.", "请先安装 Android SDK 命令行工具，再管理 SDK 软件包。"},
            {"SDK Manager was not found.", "未找到 SDK Manager。"},
            {"Could not fetch SDK package lists. Check your network connection.", "无法获取 SDK 软件包列表。请检查网络连接。"},
            {"Command-line tools are installed. Install emulator and platform-tools below.", "命令行工具已安装。请在下方安装 emulator 和 platform-tools。"},
            {"Command-line tools are missing. Install them to manage SDK packages.", "缺少命令行工具。安装后才能管理 SDK 软件包。"},
            {"Install command-line tools and required SDK packages before applying as a working SDK.", "请先安装命令行工具和必要的 SDK 软件包，再作为可用 SDK 应用。"},
            {"Install Command-line Tools", "安装命令行工具"},
            {"Install Android SDK Tools", "安装 Android SDK 工具"},
            {"Choose an empty folder for the Android SDK download.", "请选择空文件夹用于下载 Android SDK。"},
            {"SDK Packages", "SDK 软件包"},
            {"SDK Platforms", "SDK 平台"},
            {"SDK Tools", "SDK 工具"},
            {"Search SDK packages...", "搜索 SDK 软件包..."},
            {"Hide obsolete packages", "隐藏过时软件包"},
            {"Show package details", "显示软件包详情"},
            {"Fetching SDK packages from official sources...", "正在从官方源获取 SDK 软件包..."},
            {"Package", "软件包"},
            {"Size", "大小"},
            {"Revision", "修订版"},
            {"Update available", "有可用更新"},
            {"Not installed", "未安装"},
            {"No SDK packages match the current filters.", "没有匹配当前筛选条件的 SDK 软件包。"},
            {"Update", "更新"},
            {"Remove", "移除"},
            {"Clear Status", "清除状态"},
            {"Some Android SDK package licenses have not been accepted yet. To install this package, you must agree to Google's Android SDK license terms.", "部分 Android SDK 软件包许可尚未接受。要安装此软件包，你需要同意 Google 的 Android SDK 许可条款。"},
            {"Some Android SDK package licenses have not been accepted yet. To install the base SDK tools, you must agree to Google's Android SDK license terms.", "部分 Android SDK 软件包许可尚未接受。要安装基础 SDK 工具，你需要同意 Google 的 Android SDK 许可条款。"},
            {"Starting installation...", "正在开始安装..."},
            {"Installation completed.", "安装完成。"},
            {"Installation failed.", "安装失败。"},
            {"Cancelling...", "正在取消..."},
            {"Cancelled.", "已取消。"},
            {"Operation cancelled.", "操作已取消。"},
            {"Starting removal...", "正在开始移除..."},
            {"Removal completed.", "移除完成。"},
            {"Removal failed.", "移除失败。"},
            {"Preparing SDK directory...", "正在准备 SDK 目录..."},
            {"Downloading command-line tools...", "正在下载命令行工具..."},
            {"Extracting command-line tools...", "正在解压命令行工具..."},
            {"Installing command-line tools...", "正在安装命令行工具..."},
            {"Command-line tools installed.", "命令行工具已安装。"},
            {"Command-line tools installation failed.", "命令行工具安装失败。"},
            {"Command-line tools installation failed unexpectedly.", "命令行工具安装时发生未知错误。"},
            {"Installing base Android SDK packages...", "正在安装基础 Android SDK 软件包..."},
            {"Base Android SDK package installation failed.", "基础 Android SDK 软件包安装失败。"},
            {"Android SDK setup completed.", "Android SDK 设置完成。"},
            {"Android SDK setup failed.", "Android SDK 设置失败。"},
            {"Android SDK setup failed unexpectedly.", "Android SDK 设置时发生未知错误。"},
            {"Could not find an Android SDK Platform package.", "未找到 Android SDK Platform 软件包。"},
            {"Android SDK licenses must be accepted before installing packages.", "安装软件包前需要先接受 Android SDK 许可。"},
            {"Could not fetch SDK packages.", "无法获取 SDK 软件包。"},
            {"SDK package operation failed.", "SDK 软件包操作失败。"},
            {"Could not query license state.", "无法查询许可状态。"},
            {"License acceptance failed.", "许可接受失败。"},
            {"JDK", "JDK"},
            {"Java used by Android SDK command-line tools launched from CoreDeck.", "CoreDeck 启动 Android SDK 命令行工具时使用的 Java。"},
            {"JDK home", "JDK 主目录"},
            {"Path to JDK home", "JDK 主目录路径"},
            {"Leave empty to use the system default Java environment.", "留空则使用系统默认 Java 环境。"},
            {"Java executable found under this JDK home.", "已在此 JDK 主目录下找到 java 可执行文件。"},
            {"No java executable found under bin.", "未在 bin 目录下找到 java 可执行文件。"},
            {"Using the system default Java environment.", "正在使用系统默认 Java 环境。"},
            {"No Java environment detected.", "未检测到 Java 环境。"},
            {"Unable to read Java version.", "无法读取 Java 版本。"},
            {"Download managed JDK", "下载托管 JDK"},
            {"This Java version is older than 17. You can keep it, or download a managed JDK below.", "当前 Java 版本低于 17。你可以继续使用，也可以在下方下载托管 JDK。"},
            {"CoreDeck can download a user-local JDK and use it without changing your system Java.", "CoreDeck 可以下载仅当前用户使用的 JDK，不会修改系统 Java。"},
            {"Fetching JDK packages from official sources...", "正在从官方源获取 JDK 软件包..."},
            {"Could not fetch JDK packages.", "无法获取 JDK 软件包。"},
            {"No JDK packages are available for this system.", "当前系统没有可用的 JDK 软件包。"},
            {"Download & Use JDK", "下载并使用 JDK"},
            {"Preparing JDK directory...", "正在准备 JDK 目录..."},
            {"Downloading JDK...", "正在下载 JDK..."},
            {"Extracting JDK...", "正在解压 JDK..."},
            {"Installing JDK...", "正在安装 JDK..."},
            {"JDK installed.", "JDK 已安装。"},
            {"JDK installation failed.", "JDK 安装失败。"},
            {"Could not fetch JDK release list.", "无法获取 JDK 发布列表。"},
            {"No supported JDK LTS releases were found.", "未找到支持的 JDK LTS 版本。"},
            {"No JDK download URL is available.", "没有可用的 JDK 下载地址。"},
            {"Could not determine a JDK install directory.", "无法确定 JDK 安装目录。"},
            {"Choose an empty folder for the JDK download.", "请选择空文件夹用于下载 JDK。"},
            {"The selected JDK path is not a directory.", "所选 JDK 路径不是目录。"},
            {"Could not replace existing JDK directory: ", "无法替换已有 JDK 目录："},
            {"JDK download failed.", "JDK 下载失败。"},
            {"Could not extract JDK archive.", "无法解压 JDK 压缩包。"},
            {"The downloaded archive did not contain a JDK home.", "下载的压缩包中没有找到 JDK 主目录。"},
            {"JDK was installed, but java was not found under bin.", "JDK 已安装，但 bin 目录下未找到 java。"},
            {"Apply JDK Path", "应用 JDK 路径"},
            {"Use System Java", "使用系统 Java"},
            {"Use this JDK only for Android SDK command-line tools launched by CoreDeck.", "仅对 CoreDeck 启动的 Android SDK 命令行工具使用此 JDK。"},
            {"Select a valid JDK home or clear the path to use system Java.", "选择有效的 JDK 主目录，或清空路径以使用系统 Java。"},
            {"Select Android SDK directory", "选择 Android SDK 目录"},
            {"Select JDK home directory", "选择 JDK 主目录"},
            {"Version: %s", "版本：%s"},
            {"Enable auto-scrolling of output logs", "启用输出日志自动滚动"},
            {"Keep the log view pinned to the most recent line as new output arrives.", "新输出到来时，让日志视图保持在最新一行。"},
            {"Confirm before deleting an AVD", "删除 AVD 前确认"},
            {"Show a confirmation dialog when you delete a virtual device.", "删除虚拟设备时显示确认框。"},
            {"Confirm before wiping and running an AVD", "清除并运行 AVD 前确认"},
            {"Show a confirmation dialog before launching an AVD with wiped user data.", "清除用户数据并启动 AVD 前显示确认框。"},
            {"Send crash reports and diagnostics to CoreDeck", "向 CoreDeck 发送崩溃报告和诊断信息"},
            {"Share anonymous crash reports and error diagnostics (Restart Required).", "共享匿名崩溃报告和错误诊断信息（需要重启）。"},

            {"File", "文件"},
            {"Preferences...", "偏好设置..."},
            {"Quit", "退出"},
            {"Quit CoreDeck?", "退出 CoreDeck？"},
            {"CoreDeck will close. Running emulator sessions and background tasks will be stopped before exit.", "CoreDeck 将关闭。正在运行的模拟器会话和后台任务会在退出前停止。"},
            {"Quitting...", "正在退出..."},
            {"View", "视图"},
            {"Hide AVD List", "隐藏 AVD 列表"},
            {"Show AVD List", "显示 AVD 列表"},
            {"Hide Options", "隐藏选项"},
            {"Show Options", "显示选项"},
            {"Hide Details", "隐藏详情"},
            {"Show Details", "显示详情"},
            {"Hide Output Log", "隐藏输出日志"},
            {"Show Output Log", "显示输出日志"},
            {"Hide Device Explorer", "隐藏设备文件浏览器"},
            {"Show Device Explorer", "显示设备文件浏览器"},
            {"Hide Bottom Panel", "隐藏底部面板"},
            {"Show Bottom Panel", "显示底部面板"},
            {"Storage Overview", "存储概览"},
            {"Tools", "工具"},
            {"Device Explorer", "设备文件浏览器"},
            {"Open Device Explorer", "打开设备文件浏览器"},
            {"Shared Folder", "共享文件夹"},
            {"Open Shared Folder in Finder", "在 Finder 中打开共享文件夹"},
            {"Open Shared Folder in File Explorer", "在文件资源管理器中打开共享文件夹"},
            {"Open Shared Folder in File Manager", "在文件管理器中打开共享文件夹"},
            {"Open Shared Folder in Emulator", "在模拟器中打开共享文件夹"},
            {"Help", "帮助"},
            {"About CoreDeck", "关于 CoreDeck"},
            {"Check for Updates...", "检查更新..."},
            {"Version", "版本"},
            {"Build", "构建"},
            {"Official tools, polished workflow — in a friendly GUI.", "官方工具，顺手流程，友好的图形界面。"},

            {"AVDs", "AVD"},
            {"Available AVDs (Android Virtual Device)", "可用 AVD（Android Virtual Device）"},
            {"Options", "选项"},
            {"Details", "详情"},
            {"Output Log", "输出日志"},
            {"Search AVDs...", "搜索 AVD..."},
            {"Create AVD", "创建 AVD"},
            {"Refresh the AVD list", "刷新 AVD 列表"},
            {"Create new AVD", "创建新 AVD"},
            {"Run the selected AVD", "运行选中的 AVD"},
            {"Delete currently selected AVD", "删除当前选中的 AVD"},
            {"Wipe & Run", "清除并运行"},
            {"Delete", "删除"},
            {"Deleting...", "正在删除..."},
            {"Stop", "停止"},
            {"Run", "运行"},
            {"Stopping...", "正在停止..."},
            {"Ready", "就绪"},
            {"Running...", "运行中..."},
            {"Ascending", "升序"},
            {"Descending", "降序"},
            {"Rename display name", "重命名显示名称"},
            {"No AVDs found", "未找到 AVD"},
            {"No matching AVDs", "没有匹配的 AVD"},
            {"Refresh devices", "刷新设备"},
            {"Refreshing devices...", "正在刷新设备..."},
            {"Loading devices...", "正在加载设备..."},
            {"Select a device", "选择设备"},
            {"ADB was not found. Install Android SDK Platform-Tools.", "未找到 ADB。请安装 Android SDK Platform-Tools。"},
            {"ADB was not found.", "未找到 ADB。"},
            {"No device path selected.", "未选择设备路径。"},
            {"No connected devices found.", "未找到已连接设备。"},
            {"Select a running AVD first.", "请先选择一个已启动的 AVD。"},
            {"Waiting for emulator...", "等待模拟器就绪..."},
            {"Current device is offline.", "当前设备离线。"},
            {"Home", "主页"},
            {"Up", "上一级"},
            {"Refresh files", "刷新文件"},
            {"Go", "跳转"},
            {"Loading files...", "正在加载文件..."},
            {"No files found.", "未找到文件。"},
            {"Files", "文件"},
            {"Could not list device files.", "无法列出设备文件。"},
            {"Could not create shared folder on device.", "无法在设备上创建共享文件夹。"},
            {"Could not open shared folder.", "无法打开共享文件夹。"},
            {"Could not prepare shared folder.", "无法准备共享文件夹。"},
            {"Could not determine the shared folder location.", "无法确定共享文件夹位置。"},
            {"Opening shared folder in emulator...", "正在模拟器中打开共享文件夹..."},
            {"Shared folder opened.", "共享文件夹已打开。"},
            {"Syncing shared folder...", "正在同步共享文件夹..."},
            {"Syncing shared folder from emulator...", "正在从模拟器同步共享文件夹..."},
            {"Shared folder synced.", "共享文件夹已同步。"},
            {"Could not sync shared folder.", "无法同步共享文件夹。"},
            {"Operation completed.", "操作完成。"},
            {"Operation failed.", "操作失败。"},
            {"Directory", "目录"},
            {"Symlink", "符号链接"},
            {"Modified", "修改时间"},
            {"Permissions", "权限"},
            {"Upload", "上传"},
            {"Upload File", "上传文件"},
            {"Upload Folder", "上传文件夹"},
            {"Uploading...", "正在上传..."},
            {"Downloading...", "正在下载..."},
            {"Create Folder", "新建文件夹"},
            {"Folder name", "文件夹名称"},
            {"Invalid folder name.", "文件夹名称无效。"},
            {"Creating folder...", "正在创建文件夹..."},
            {"Choose download folder", "选择下载目录"},
            {"Select file to upload", "选择要上传的文件"},
            {"Select folder to upload", "选择要上传的文件夹"},
            {"This will permanently delete the selected file or folder from the Android device.", "这会从 Android 设备永久删除选中的文件或文件夹。"},
            {"All device directories are supported, including system paths. Double-check before deleting. This cannot be undone.", "设备上的所有目录都支持操作，包括系统路径。删除前请再次确认，删除后无法撤销。"},
            {"Select an AVD to view details", "选择一个 AVD 查看详情"},
            {"Select an AVD to configure options", "选择一个 AVD 配置选项"},
            {"Display Name", "显示名称"},
            {"Internal Name", "内部名称"},
            {"Device", "设备"},
            {"API Level", "API 级别"},
            {"ABI", "ABI"},
            {"Arch", "架构"},
            {"RAM", "内存"},
            {"Resolution", "分辨率"},
            {"Storage", "存储"},
            {"GPU Mode", "GPU 模式"},
            {"Skin", "皮肤"},
            {"None", "无"},
            {"Default", "默认"},
            {"Google Play", "Google Play"},
            {"Google APIs", "Google APIs"},
            {"Supported", "支持"},
            {"Not supported", "不支持"},
            {"Type", "类型"},
            {"16 KB Page Size", "16 KB 页大小"},
            {"Tags", "标签"},
            {"Live Resource Usage", "实时资源占用"},
            {"CPU Usage", "CPU 占用"},
            {"Memory", "内存"},
            {"Disk Usage", "磁盘占用"},
            {"Current CPU", "当前 CPU"},
            {"Current Memory", "当前内存"},
            {"Disk Read Rate", "磁盘读取速率"},
            {"Disk Write Rate", "磁盘写入速率"},
            {"Uptime", "运行时间"},
            {"Wipe User Data", "清除用户数据"},
            {"Stop the emulator before wiping data", "清除数据前请先停止模拟器"},
            {"Wipe", "清除"},
            {"Cancel", "取消"},
            {"Starting...", "正在启动..."},
            {"Wiping...", "正在清除..."},
            {"Wipe and run", "清除并运行"},
            {"This will reset the selected AVD to factory defaults before launching it. User data cannot be recovered.", "这会在启动前将选中的 AVD 恢复为出厂状态，用户数据无法恢复。"},
            {"This will permanently remove the AVD and all its data. This action cannot be undone.", "这会永久删除该 AVD 及其所有数据，此操作无法撤销。"},
            {"This will delete userdata, cache, SD card images, and snapshots for this AVD. This cannot be undone.\n\nContinue?", "这会删除该 AVD 的用户数据、缓存、SD 卡镜像和快照，无法撤销。\n\n继续吗？"},

            {"Create New AVD", "创建新 AVD"},
            {"AVD Name", "AVD 名称"},
            {"Name", "名称"},
            {"e.g. MyPixel7", "例如 MyPixel7"},
            {"e.g. My Pixel 7", "例如 My Pixel 7"},
            {"An AVD named \"%s\" already exists.", "名为 \"%s\" 的 AVD 已存在。"},
            {"System Image", "系统镜像"},
            {"No system images available. Install one...", "没有可用系统镜像。安装一个..."},
            {"No system images installed", "未安装系统镜像"},
            {"SDK Manager was not found, so CoreDeck cannot install images automatically.", "未找到 SDK Manager，CoreDeck 无法自动安装镜像。"},
            {"Loading system images...", "正在加载系统镜像..."},
            {"Loading device profiles...", "正在加载设备配置..."},
            {"No device profiles found.", "未找到设备配置。"},
            {"CoreDeck will use avdmanager's default hardware profile.", "CoreDeck 将使用 avdmanager 的默认硬件配置。"},
            {"No skin", "无皮肤"},
            {"No skin (plain emulator window)", "无皮肤（普通模拟器窗口）"},
            {"Loading skins...", "正在加载皮肤..."},
            {"RAM (MB)", "内存 (MB)"},
            {"SD Card Size", "SD 卡大小"},
            {"e.g. 2048 (MB)", "例如 2048 (MB)"},
            {"e.g. 512 (MB)", "例如 512 (MB)"},
            {"Hardware Acceleration", "硬件加速"},
            {"Software Rendering", "软件渲染"},
            {"ANGLE Rendering", "ANGLE 渲染"},
            {"Guest Rendering", "Guest 渲染"},
            {"Create", "创建"},
            {"Creating...", "正在创建..."},
            {"Choose Device Profile", "选择设备配置"},
            {"Search device profiles...", "搜索设备配置..."},
            {"Categories", "分类"},
            {"All", "全部"},
            {"Phone / Tablet", "手机 / 平板"},
            {"Phone", "手机"},
            {"Tablet", "平板"},
            {"Wear OS", "Wear OS"},
            {"TV", "电视"},
            {"Automotive", "车载"},
            {"Desktop", "桌面"},
            {"XR", "XR"},
            {"Other", "其他"},
            {"Device Profiles", "设备配置"},
            {"No device profiles match the selected form factor and search.", "没有匹配当前类型和搜索条件的设备配置。"},
            {"Use Selected Device", "使用所选设备"},
            {"Choose Skin", "选择皮肤"},
            {"Search skins...", "搜索皮肤..."},
            {"Skins", "皮肤"},
            {"Source", "来源"},
            {"SDK", "SDK"},
            {"Platform", "平台"},
            {"No skins match the search.", "没有匹配搜索条件的皮肤。"},
            {"No skins were found in your SDK. Skins typically ship with system images and the SDK skins folder.", "你的 SDK 中未找到皮肤。皮肤通常随系统镜像和 SDK skins 文件夹提供。"},
            {"Use Selected Skin", "使用所选皮肤"},

            {"Install System Image", "安装系统镜像"},
            {"Search for a system image by name", "按名称搜索系统镜像"},
            {"Images", "镜像"},
            {"Installed", "已安装"},
            {"System Images", "系统镜像"},
            {"Fetching available images from SDK manager...", "正在从 SDK Manager 获取可用镜像..."},
            {"No remote system images found. Check your SDK and internet connection.", "未找到远程系统镜像。请检查 SDK 和网络连接。"},
            {"Status", "状态"},
            {"Available", "可用"},
            {"No system images match the current filters.", "没有匹配当前筛选条件的系统镜像。"},
            {"Use Selected Image", "使用所选镜像"},
            {"Remove Image", "移除镜像"},
            {"Removing...", "正在移除..."},
            {"Close", "关闭"},
            {"Install", "安装"},
            {"Installing...", "正在安装..."},
            {"Checking licenses...", "正在检查许可..."},
            {"Accept Android SDK License Terms", "接受 Android SDK 许可条款"},
            {"Some Android SDK package licenses have not been accepted yet. To install this system image, you must agree to Google's Android SDK license terms. By clicking Agree, you confirm that you have read and accept the current terms.", "部分 Android SDK 包许可尚未接受。要安装此系统镜像，你需要同意 Google 的 Android SDK 许可条款。点击同意即表示你已阅读并接受当前条款。"},
            {"Open license terms in browser", "在浏览器中打开许可条款"},
            {"Recording acceptance with the SDK Manager...", "正在通过 SDK Manager 记录许可接受状态..."},
            {"Agree & Install", "同意并安装"},
            {"Could not query license state. Check that the SDK Manager is working.", "无法查询许可状态。请检查 SDK Manager 是否可用。"},
            {"License acceptance failed. Try again or accept via Android Studio.", "许可接受失败。请重试，或通过 Android Studio 接受。"},

            {"Rename Display Name", "重命名显示名称"},
            {"Leave empty to use the internal name", "留空则使用内部名称"},
            {"Internal name remains unchanged: %s", "内部名称保持不变：%s"},
            {"Save", "保存"},
            {"Invalid display name.", "显示名称无效。"},
            {"Display name is unchanged.", "显示名称未改变。"},
            {"Failed to update display name.", "更新显示名称失败。"},
            {"Failed to update the AVD config file.", "更新 AVD 配置文件失败。"},

            {"Up to date", "已是最新"},
            {"You're running the latest CoreDeck release.", "你正在运行最新的 CoreDeck 版本。"},
            {"Current: ", "当前："},
            {"OK", "确定"},
            {"Update Available", "有可用更新"},
            {"You're currently running on", "当前运行版本"},
            {"Download", "下载"},
            {"Later", "稍后"},

            {"Total Storage", "总存储"},
            {"Calculating...", "正在计算..."},
            {"Calculated from local SDK and AVD folders", "根据本地 SDK 和 AVD 文件夹计算"},
            {"Statistics", "统计"},
            {"Breakdown", "明细"},
            {"Refresh", "刷新"},
            {"Refreshing...", "正在刷新..."},
            {"No working Android SDK was detected (the emulator binary is missing or the path is invalid).", "未检测到可用的 Android SDK（emulator 二进制缺失或路径无效）。"},
            {"Configure SDK", "配置 SDK"},
            {"Dismiss for this session", "本次会话忽略"},
            {"Your Android emulator command center.", "你的 Android 模拟器命令中心。"},
            {"Welcome! CoreDeck helps you manage Android emulators", "欢迎！CoreDeck 帮你管理 Android 模拟器"},
            {"faster and cleaner than the default tooling.", "比默认工具更快、更清爽。"},
            {"Get Started", "开始使用"},
            {"Configure Java", "配置 Java"},
            {"CoreDeck uses Java to run Android SDK command-line tools.", "CoreDeck 使用 Java 运行 Android SDK 命令行工具。"},
            {"JDK 17 or later is recommended for modern Android SDK tools.", "现代 Android SDK 工具建议使用 JDK 17 或更高版本。"},
            {"Locate your Android SDK", "定位你的 Android SDK"},
            {"CoreDeck needs to know where your Android SDK lives.", "CoreDeck 需要知道你的 Android SDK 位置。"},
            {"This is where 'emulator', 'avdmanager' and system images are installed.", "这里安装了 emulator、avdmanager 和系统镜像。"},
            {"SDK path", "SDK 路径"},
            {"e.g. /Users/you/Library/Android/sdk", "例如 /Users/you/Library/Android/sdk"},
            {"Select your Android SDK folder", "选择你的 Android SDK 文件夹"},
            {"Looks good. Found the Android emulator at this location.", "看起来没问题，已在此位置找到 Android emulator。"},
            {"Command-line tools are installed. Continue and install emulator and platform-tools from Android SDK preferences.", "命令行工具已安装。继续后可在 Android SDK 偏好设置中安装 emulator 和 platform-tools。"},
            {"Command-line tools are missing. Install them here or choose an existing SDK root.", "缺少命令行工具。请在此安装，或选择已有的 SDK 根目录。"},
            {"Android SDK tools are incomplete. Install the base tools here, or continue and finish later from Android SDK preferences.", "Android SDK 工具不完整。可在此安装基础工具，或继续后在 Android SDK 偏好设置中完成。"},
            {"Android SDK tools are missing. Install the base tools here or choose an existing SDK root.", "缺少 Android SDK 工具。请在此安装基础工具，或选择已有的 SDK 根目录。"},
            {"Couldn't find the Android emulator here. Make sure this is your SDK root folder.", "这里找不到 Android emulator。请确认这是 SDK 根目录。"},
            {"Choose the folder containing your Android SDK (cmdline-tools, emulator, platform-tools, etc).", "选择包含 Android SDK 的文件夹（cmdline-tools、emulator、platform-tools 等）。"},
            {"Back", "返回"},
            {"Continue", "继续"},
            {"Select an AVD to view logs", "选择一个 AVD 查看日志"},
            {"No available logs to view", "没有可查看的日志"},
            {"No matching log entries found", "没有匹配的日志条目"},
            {"Search logs...", "搜索日志..."},
            {"Regex", "正则"},
            {"Invalid regex: %s", "无效正则：%s"},
            {"Run the \"%s\" AVD to view logs", "运行 \"%s\" AVD 后查看日志"},
            {"Author", "作者"},
            {"License", "许可证"},
            {"Website", "网站"},
            {"Built with", "构建技术"},
            {"Version %s (Build %s)", "版本 %s（构建 %s）"},

            {"Display", "显示"},
            {"Performance", "性能"},
            {"Boot", "启动"},
            {"Audio", "音频"},
            {"Network", "网络"},
            {"Advanced", "高级"},
            {"Camera", "摄像头"},
            {"System", "系统"},
            {"Location", "位置"},
            {"Set hardware OpenGLES emulation mode", "设置硬件 OpenGLES 模拟模式"},
            {"Screen Mode", "屏幕模式"},
            {"Set emulated screen mode", "设置模拟屏幕模式"},
            {"Device DPI", "设备 DPI"},
            {"Override the device's screen density in dpi", "覆盖设备屏幕密度（dpi）"},
            {"Disable Skin", "禁用皮肤"},
            {"Run without any device skin", "运行时不使用设备皮肤"},
            {"Select a specific device skin by name", "按名称选择指定设备皮肤"},
            {"Window Size", "窗口大小"},
            {"Set the initial emulator window size (useful with no-skin)", "设置模拟器初始窗口大小（无皮肤时有用）"},
            {"Physical RAM (MBs)", "物理内存 (MB)"},
            {"Physical RAM size in MBs", "物理内存大小（MB）"},
            {"CPU Cores", "CPU 核心数"},
            {"Set number of CPU cores for the emulator", "设置模拟器 CPU 核心数"},
            {"Cache Size (MBs)", "缓存大小 (MB)"},
            {"Cache partition size in MBs", "缓存分区大小（MB）"},
            {"Full Boot", "完整启动"},
            {"Perform a full boot and do not auto-save on exit", "执行完整启动，退出时不自动保存"},
            {"Cold Boot", "冷启动"},
            {"Perform a full boot without loading a snapshot (preserves user data)", "不加载快照并完整启动（保留用户数据）"},
            {"Discard State on Exit", "退出时丢弃状态"},
            {"Do not auto-save to snapshot on exit; changed state is abandoned", "退出时不自动保存快照，放弃已变更状态"},
            {"Snapshot Name", "快照名称"},
            {"Name of the snapshot to auto-start from and auto-save to", "自动启动和自动保存使用的快照名称"},
            {"Read-Only (Multi-Instance)", "只读（多实例）"},
            {"Allow running multiple instances of this AVD (snapshots cannot be saved)", "允许同时运行该 AVD 的多个实例（无法保存快照）"},
            {"Factory Reset", "恢复出厂设置"},
            {"Reset AVD to factory defaults (clears user data)", "将 AVD 恢复到出厂状态（清除用户数据）"},
            {"Skip Boot Animation", "跳过启动动画"},
            {"Disable boot animation for faster startup", "禁用启动动画以加快启动"},
            {"Disable Audio", "禁用音频"},
            {"Disable audio support", "禁用音频支持"},
            {"Allow Host Microphone", "允许主机麦克风"},
            {"Pass host audio input devices through to the guest (otherwise zeroed)", "将主机音频输入设备传递给客户系统（否则置零）"},
            {"Network Speed", "网络速度"},
            {"Simulate network download/upload speed", "模拟网络下载/上传速度"},
            {"Network Delay", "网络延迟"},
            {"Simulate network latency", "模拟网络延迟"},
            {"HTTP Proxy", "HTTP 代理"},
            {"Route network traffic through a HTTP/HTTPS proxy (e.g., Charles, mitmproxy)", "通过 HTTP/HTTPS 代理路由网络流量（例如 Charles、mitmproxy）"},
            {"DNS Server", "DNS 服务器"},
            {"Use custom DNS server(s) in the emulated system", "在模拟系统中使用自定义 DNS 服务器"},
            {"Packet Capture File", "抓包文件"},
            {"Capture network packets to the given pcap file", "将网络包捕获到指定 pcap 文件"},
            {"Console Port", "控制台端口"},
            {"TCP port used for the emulator console (adb port is console + 1)", "模拟器控制台使用的 TCP 端口（adb 端口为控制台端口 + 1）"},
            {"Console + ADB Ports", "控制台 + ADB 端口"},
            {"TCP ports used for the console and adb bridge", "控制台和 adb bridge 使用的 TCP 端口"},
            {"Back Camera", "后置摄像头"},
            {"Set emulation mode for the back-facing camera", "设置后置摄像头模拟模式"},
            {"Front Camera", "前置摄像头"},
            {"Set emulation mode for the front-facing camera", "设置前置摄像头模拟模式"},
            {"Disable Passive GPS", "禁用被动 GPS"},
            {"Disable passive GPS updates from the host", "禁用来自主机的被动 GPS 更新"},
            {"GNSS Replay File", "GNSS 回放文件"},
            {"Read GNSS data from the given file to replay a route", "从指定文件读取 GNSS 数据以回放路线"},
            {"Phone Number", "电话号码"},
            {"Set the phone number reported by the emulated device", "设置模拟设备报告的电话号码"},
            {"Locale", "区域设置"},
            {"Override the device locale (restarts the framework)", "覆盖设备区域设置（会重启 framework）"},
            {"Writable System", "可写系统"},
            {"Make the system and vendor images writable after 'adb remount'", "在 'adb remount' 后使 system 和 vendor 镜像可写"},
            {"Skip ADB Auth", "跳过 ADB 认证"},
            {"Skip the adb authentication dialog on connect", "连接时跳过 adb 认证对话框"},
            {"Instance ID", "实例 ID"},
            {"Assign a separate id to this virtual device (independent of the AVD name)", "为此虚拟设备分配独立 id（不依赖 AVD 名称）"},
            {"System Property", "系统属性"},
            {"Set a system property on boot (single name=value pair)", "启动时设置系统属性（单个 name=value）"},
            {"Emulator Features", "模拟器特性"},
            {"Force-enable or disable (-name) emulator features", "强制启用或禁用（-name）模拟器特性"},
            {"Headless Mode", "无窗口模式"},
            {"Run without graphical window display (useful for CI/testing)", "不显示图形窗口运行（适合 CI/测试）"},
            {"Show Kernel Log", "显示内核日志"},
            {"Display kernel messages in the output log", "在输出日志中显示内核消息"},
            {"Verbose Logging", "详细日志"},
            {"Enable verbose emulator logging (same as -debug-init)", "启用详细模拟器日志（等同于 -debug-init）"},
            {"Wait for Debugger", "等待调试器"},
            {"Pause on launch until a debugger process attaches", "启动后暂停，直到调试器进程附加"},
            {"Disable HiDPI", "禁用 HiDPI"},
            {"Disable HiDPI scaling on macOS Retina displays", "禁用 macOS Retina 显示器上的 HiDPI 缩放"},
            {"Partition Size (MBs)", "分区大小 (MB)"},
            {"System/data partition size in MBs", "system/data 分区大小（MB）"},
            {"Logcat Tags", "Logcat 标签"},
            {"Enable logcat output with specific tags", "启用指定标签的 logcat 输出"},
            {"Timezone", "时区"},
            {"Use a specific timezone instead of the host's default", "使用指定时区而非主机默认时区"},
            {"Acceleration Mode", "加速模式"},
            {"Configure emulation acceleration", "配置模拟器加速"},
            {"SELinux Mode", "SELinux 模式"},
            {"Set SELinux to disabled or permissive mode", "将 SELinux 设置为 disabled 或 permissive"},
            {"Override the initial system image file", "覆盖初始系统镜像文件"},
            {"Userdata Image", "用户数据镜像"},
            {"Override the userdata image file", "覆盖用户数据镜像文件"},
            {"SD Card Image", "SD 卡镜像"},
            {"Override the SD card image file", "覆盖 SD 卡镜像文件"},
            {"Restart When Stalled", "卡住时重启"},
            {"Automatically restart the guest if it becomes unresponsive", "客户系统无响应时自动重启"},
            {"Detect Image Hangs", "检测镜像卡死"},
            {"Enable detection of system image hangs", "启用系统镜像卡死检测"},
            {"Touch Screen", "触摸屏"},
            {"Multi-Touch Screen", "多点触控屏"},
            {"No Touch Input", "无触摸输入"},
            {"Full Speed", "全速"},
            {"No Delay", "无延迟"},
            {"GPRS Latency", "GPRS 延迟"},
            {"EDGE Latency", "EDGE 延迟"},
            {"UMTS Latency", "UMTS 延迟"},
            {"Disabled", "禁用"},
            {"Enabled", "启用"},
            {"Permissive", "宽容模式"},
            {"Virtual Scene", "虚拟场景"},
            {"Emulated", "模拟"},
        };

        std::string PreserveImGuiId(const char *label, const char *translated) {
            if (label == nullptr) {
                return "";
            }
            const std::string_view original(label);
            const std::size_t idPos = original.find("##");
            if (idPos == std::string_view::npos) {
                return translated;
            }
            std::string result(translated);
            result.append(original.substr(idPos));
            return result;
        }
    }

    void SetCurrentLanguage(const AppLanguage language) {
        currentLanguage = language;
    }

    AppLanguage GetCurrentLanguage() {
        return currentLanguage;
    }

    const char *LanguageDisplayName(const AppLanguage language) {
        switch (language) {
            case AppLanguage::SimplifiedChinese:
                return "简体中文";
            case AppLanguage::English:
            default:
                return "English";
        }
    }

    const char *Tr(const char *text) {
        if (text == nullptr || currentLanguage == AppLanguage::English) {
            return text;
        }
        if (const auto it = ZH_CN.find(text); it != ZH_CN.end()) {
            return it->second;
        }
        return text;
    }

    std::string TrLabel(const char *label) {
        if (label == nullptr) {
            return "";
        }
        const std::string_view original(label);
        const std::size_t idPos = original.find("##");
        const std::string_view visible = idPos == std::string_view::npos ? original : original.substr(0, idPos);
        const std::string visibleString(visible);
        return PreserveImGuiId(label, Tr(visibleString.c_str()));
    }

    const char *SimplifiedChineseGlyphText() {
        static const std::string glyphText = [] {
            std::string text = "简体中文";
            for (const auto &[_, value]: ZH_CN) {
                text += value;
                text += '\n';
            }
            return text;
        }();
        return glyphText.c_str();
    }
}
